### PR TITLE
Autocomplete for Files and Directories

### PR DESCRIPTION
**Pull request by John-Nenniger**
#20, makes tab completion work for files and directories for any number of arguments (though it only autocompletes the last word)

I ended up just using `TerminalUtilites.getFsUnit` within the autoCompleteFiles function instead of doing a more significant refactor, which looks okay to me, though I can do more of a refactor if wanted.

### CODE REVIEW

**Comment by syntaxseed** [comment]
This PR needs a rebase. 
We just refactored the project in PR #23 to use ES6 and WebPack.

**Comment by John-Nenniger** [comment]
This is ready to go now.  Sorry about all the commits, I haven't done a lot of rebasing so i left in some code I shouldn't have.

After the PR #23 autocompleting the commands only works with some commands (the ones defined in customCommands.js), and this branch doesn't fix that problem: #27

**Comment by syntaxseed** [comment]
I'd prefer to have this completely working, and without some old code left in. I'm already concerned that the codebase is getting pretty disorganized. Especially with a PR this large. If you have time @John-Nenniger to put the finishing touches on it, that would be great. No rush. I am taking a bit of a break over the Christmas season.

Thanks!

**Comment by syntaxseed** [comment]
Awesome I will check this out soon.

**Comment by syntaxseed** [comment]
This is absolutely awesome. It doesn't work with the ls command for some reason, maybe because it's too short?

Regardless, thanks for this PR, really nice enhancement to this project. :+1:

**Comment by syntaxseed** [comment]
Thanks again @John-Nenniger. Added you to the contributors list in the readme. :)

**Pull request merged**
