### PR TITLE
Add eventListener on click to re-focus input

### LINKED ISSUE #21: Input can be difficult to re-focus
I made a fix for this earlier but forgot to branch it so it went to master. I reverted it to keep the issue/PR stream cleaner.

I'll open a pull request with the fix (an `eventListener` on the window that focuses the input).

### PR DESCRIPTION
**Pull request by ghost**
Fixes #21

### CODE REVIEW

**Comment by syntaxseed** [comment]
There are a number of event listeners defined in the Terminal object in `js/src/terminal.js`. Can you move the event listener set up into there to keep the html file clean and keep all the event listeners together? You should be able to use the `elem` variable found in there which is the terminal div.

**Comment by ghost** [comment]
Got that done.

**Comment by syntaxseed** [comment]
Thanks for working on this.
Quick tip: It looks like you have some kind of automatic code formatter - maybe in your IDE. It's a good idea to turn these off when working on someone else's project because your PR is cluttered with re-formatting of the existing code. Converting quotes and re-indenting and spacing things. Makes it hard to pick out what really changed and it is converting someone else's code style.

I'm going to pick your changes out manually and apply them to the master branch, to avoid all the re-formatting.

I really like this change - I think it's a nice improvement and was something that bugged me as well. Thanks for contributing!

**Comment by ghost** [comment]
Sorry, didn't think of the code formatting. Do you have a particular style guide you follow? An ESLint config might be a good idea for an issue?

**Comment by syntaxseed** [comment]
I don't... but that's a good idea.

**Comment by syntaxseed** [comment]
Modified this slightly so that users can still hightlight text in the terminal window.

```javascript
        /**
         * Help with re-focusing the contenteditable input line when the terminal div is clicked.
         */
        elem.addEventListener("mouseup", () => {
            if (typeof window.getSelection != "undefined") {
                var text = window.getSelection().toString();
                if (text == ''){
                    // If the user is not highlighting text, focus our input.
                    document.querySelector("#terminal p:last-child span:last-child").focus();
                }
            }
        });
```

**Comment by syntaxseed** [comment]
Merged manually. Thank you @jacob-shu !

**Pull request closed without merging**
